name: Deploy lambda
# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Zip the code
        run: zip -r lambda_function.zip .
      - name: Deploy to AWS Lambda
        run: |
          if aws lambda get-function --function-name example-lambda-aws-cli > /dev/null 2>&1; then
            echo "Function exists, updating..."
            aws lambda update-function-code --function-name example-lambda-aws-cli --zip-file fileb://lambda_function.zip
          else
            echo "Function does not exist, creating..."
            aws lambda create-function --function-name example-lambda-aws-cli --runtime nodejs18.x --handler index.handler --zip-file fileb://lambda_function.zip
          fi